# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87a62293e144a2230f6d06c0b8623ee51f812c6d71251c746d1bf54dcda23055cb17210053b3becb5811a890137f548dde857cbfd85ce2923ef86966151eb7d

test:
  secret_key_base: 8925ff2f0227eb490317ec9710e2f626186afc50f7c07c4042615a4667b26988d3ea953a9c1810cb8f076ba477b7cd6dcf51394d33af86c947ab56ef190f8df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
